### ISSUE TITLE
Build issue: Missing file Model.xcdatamodeld

### ISSUE THREAD

**Issue by hachidorii** [Antidote-for-Tox/Antidote#105]
I tried to build it but the model file is missing.

**Comment by dvor** [comment]
Hm, everything works for me in Xcode 6.4

Anyway, indeed there was outdated `Model.xcdatamodeld` in project. I've removed it as now we use Realm instead. Should work fine now (just in case - don't forget to do `pod install` and open `Antidote.xcworkspace`).
