### ISSUE TITLE
Fix autolayout for Dialing and Ringing view controllers

### ISSUE THREAD

**Issue by Chuongv** [Antidote-for-Tox/Antidote#110]
They should support autolayout.

**Comment by Chuongv** [comment]
Actually looking at skype, they support rotation. @dvor  what do you think?

**Comment by dvor** [comment]
Well, it would be nice to support rotation. However it will take some work. I would suggest to leave it for now, lock orientation and polish thing that are already there (maybe investigate video quality issue as well).

Next Monday is already "pencils down" day.

**Comment by Chuongv** [comment]
Okay, I change the issue's title to support this feature instead.
