### ISSUE TITLE
After disabling video screen stays black for 5-7 seconds

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#121]
- there is outgoing video
- there is **no** incoming video

I turn video off and screen stays black & shows old preview for some time.

I think it is issue with updating UI *not* on main thread.

**Comment by Chuongv** [comment]
I wasn't able to reproduce this anymore, it may have been fixed by https://github.com/Antidote-for-Tox/Antidote/pull/129
