### ISSUE TITLE
Fix video proportions

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#122]
Video/preview shouldn't fill whole screen, it should keep right proportions. See screenshot

![img_8738](https://cloud.githubusercontent.com/assets/1132979/9341728/efa5d55c-45f7-11e5-8901-4dd038346870.PNG)

**Comment by Chuongv** [comment]
Depends on https://github.com/Antidote-for-Tox/objcTox/issues/119

**Comment by Chuongv** [comment]
Hmm thinking this over. You want it to be the same size, no matter what resolution correct? So we do want scaling, just not filling up the whole screen?

**Comment by dvor** [comment]
Video should be maximum size but with correct proportions. E.g. if we have video 100x100 and screen is 320x480, video view would have size 320x320 but not 320x480.

**Comment by Chuongv** [comment]
Closed, fixed in objcTox
