### ISSUE TITLE
Wrong video controls when going from landscape to portrait

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#123]
- there is outgoing video
- there is **no** incoming video
- iPhone has portrait orientation
- go to landscape, go back to portrait
- wrong controls are shown

See screenshot

![img_5306](https://cloud.githubusercontent.com/assets/1132979/9341788/3bcd7c50-45f8-11e5-9a23-3e20f477bb3e.PNG)

**Comment by Chuongv** [comment]
Fixed by https://github.com/Antidote-for-Tox/Antidote/pull/129
