### ISSUE TITLE
Add camera switch to top right corner, move "hold calls" button to the left

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#124]
- "hold calls" button must be moved to top-left corner
- camera switch button should be added to the top-right corner
    - this button should be visible **only** if there is outgoing video

See mockups

> no outgoing video - no button
![video call - vertical incoming only](https://cloud.githubusercontent.com/assets/1132979/9341954/57652f7a-45f9-11e5-8256-4ef9e92f91af.png)

---

> ![video call - horizontal](https://cloud.githubusercontent.com/assets/1132979/9341960/6403d330-45f9-11e5-92e7-7558c64c991b.png)

---

> moving "hold calls" to the left
![video call - see holded calls](https://cloud.githubusercontent.com/assets/1132979/9341968/733af2de-45f9-11e5-8847-85f5876be00c.png)

**Comment by Chuongv** [comment]
Depends on https://github.com/Antidote-for-Tox/objcTox/issues/85

**Comment by dvor** [comment]
Done
