### ISSUE TITLE
No need to send "new message" notification after the call

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#125]
- open *not* chat screen
- receive incoming call
- end call
- new OCTMessage is added and notification on top is displayed

This message should be ignored by `NotificationManager` and notification should be removed.

**Comment by Chuongv** [comment]
Should all message calls be ignored? I can't find a reason why it needs to be shown.

**Comment by dvor** [comment]
You mean messages that have `message.messageCall`? Well yes, I think so.
