### ISSUE TITLE
Nickname shouldn't be empty

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#142]
- user can delete nickname of friend *or*
- friend can delete her own name

In that case friend's nickname should be set back to Tox ID

**Comment by zetok** [comment]
Why user shouldn't be allowed to set an empty name?

**Comment by dvor** [comment]
Sorry, the description is not accurate enough. It was about friend's nickname. User *can* delete friend's nickname or friend can delete her name. In this case client should fallback to showing default one = showing Tox ID

Will update issue.

**Comment by dvor** [comment]
Also name != nickname. nickname = alias.

**Comment by zetok** [comment]
>Also name != nickname. nickname = alias.

Oh, this way.

**Comment by dvor** [comment]
https://github.com/Antidote-for-Tox/objcTox/issues/135

**Comment by dvor** [comment]
Fixed in objcTox
