### ISSUE TITLE
give usernames @antidote.im

### ISSUE THREAD

**Issue by iShift** [Antidote-for-Tox/Antidote#146]
If you can git username with @antidote.im you can bring tox for non geek users. 
__ 
Давно тестирую антидот в teshflight, работает хорошо, но на мой взгляд что бы больше людей смогло его использовать стоит при генерации TOX-ID выдавать username на адресе antidote.im, стандарт же с DNS есть

**Comment by dvor** [comment]
Yes, I was thinking about that. However for that I need
- server
- set up toxdns on that server
- time :-)

**Comment by dvor** [comment]
Also working on
- file transfers
- groupchats
- audio calls
- video calls

seems to have higher priority to me.

**Comment by iShift** [comment]
i can help you with 
>server
>set up toxdns on that server

**Comment by dvor** [comment]
@iShift  can you please please email me about that because I lost your email address %)

**Comment by dvor** [comment]
Non needed as DNS will die soon (hopefully). See https://github.com/TokTok/c-toxcore/issues/192
