### ISSUE TITLE
Paused call view is shown below call controls

### ISSUE THREAD

**Issue by Chuongv** [Antidote-for-Tox/Antidote#158]
Alice is in a call with Bob, Carol calls Alice. Alice accepts the call which puts Bob on hold. When clicking on the call menu, it should cover up the call controls.

![img_1834](https://cloud.githubusercontent.com/assets/5170710/9823980/a55ef0fc-587e-11e5-9c9f-cba6fd0e31e0.PNG)

**Comment by dvor** [comment]
Not relevant after Swift rewrite
