### ISSUE TITLE
Implement Tox Client Standard concerning the avatars

### ISSUE THREAD

**Issue by ovalseven8** [Antidote-for-Tox/Antidote#166]
>2.3.5 Clients must display avatars at a 1:1 aspect ratio.
>
>2.3.6 A client may only transmit avatars with an aspect ratio of 1:1. If the user has chosen a non-square avatar, the client must transmit the square portion of the avatar displayed to the user. In the case that the user's client doesn't display avatars, the client must pad the avatar evenly on two sides with transparent rectangles, in order to create a square.

Further explanations -> https://github.com/Tox/Tox-Client-Standard/pull/13#issuecomment-149243360

**Comment by dvor** [comment]
Done
