### ISSUE TITLE
Please kindly help me regarding iPhone 4

### ISSUE THREAD

**Issue by darkman088** [Antidote-for-Tox/Antidote#168]
Hello

I am getting REALLY desperate with an iPhone 4 that I have available.
I want to use it for secure communication but it is stuck with iOS 7 and
all the apps require 8!!!
I am using tox on PC and on the iPhone would be great as well, just
Antidote wants iOS 8 as well!!! Please tell me if it is possible to use
some older version or just suggest something please! As you obviously 
got it, I am an iPhone greenhorn :P
Thanks a lot!!!

**Comment by dvor** [comment]
Hi @darkman088 

Sorry, but supporting iOS versions prior to 8 would require too much effort. Unfortunately I cannot suggest you anything.

**Comment by darkman088** [comment]
Hey, what about an older version ?
It has been working at some point in time on iOS 7, hasn't it ?

Thanks!

**Comment by dvor** [comment]
Well, you are right. There are two options of installing it:
- you can build old version of Antidote yourself using Xcode on OS X (if you want to do that I can help you)
- if your iPhone is jailbroken I can create a build for you

**Comment by darkman088** [comment]
Hello dvor,

thank you! That's the thing - I don't own the phone, hence I can't jailbreak it :-/
Otherwise I would have installed Threema...
I have heard of Xcode while looking for a way to deploy an .ipa file without jailbreaking the device.
But the thing is, that I don't have a Mac computer which I can use. Probably this would require
installing MacOS X in a VM, which I have done before as well...
Can you please kindly make a very brief description of the steps, without going into any details
for now, so that I can estimate how complicated that is and how much time it will cost me.
I would buy Threema, it costs just 2 Euro, just I don't feel comfortable providing any credit card data to the apple store...

**Comment by dvor** [comment]
Briefly you have to do following:

1. Get OS X and install Xcode from AppStore
2. Install [CocoaPods](https://cocoapods.org/)
3. [Download](https://github.com/Antidote-for-Tox/Antidote/archive/35d0a6f75737193f0d209c5639ef7fedf6d4d016.zip) Antidote
4. Run install script `./install.sh`
5. Open Antidote.xcworkspace with Xcode and run app on your iPhone.

You can find an instruction on how to run app on iPhone without developer profile [here](https://developer.apple.com/library/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html#//apple_ref/doc/uid/TP40012582-CH27)
