### ISSUE TITLE
Voiceover and button labels

### ISSUE THREAD

**Issue by tyrylu** [Antidote-for-Tox/Antidote#169]
When using voiceover to look around the interface, the main section switching buttons (e. g. those which open the friends list and settings) are read asjust button without any label.
For example, the friends/requests switcher buttons are read just fine.
I do not have an IOS dev environment, so i unfortunately can not test any pull request, so this issue must be enough...

**Comment by dvor** [comment]
Thanks for reporting. I'm planning to work on that one day. There is already another issue for that.

https://github.com/Antidote-for-Tox/Antidote/issues/115
