### ISSUE TITLE
Sending files from other apps issues

### ISSUE THREAD

**Issue by masvil** [Antidote-for-Tox/Antidote#193]
I'm testing the new feature pushing file from Documents by Readdle as it's the most popular iOS "file manager".

1. Antidote crashes MOST of times I try to do it.
2. If Antidote fails to send for any reason I can't send again without go back to Documents by Readdle.
3. After sent (or failed to) I can't delete file neither forward. It means Antidote internal storage will be full of useless files.
4. If I try to push a file having an "unknown" extension from Documents by Readdle then Antidote doesn't show in the list.
5. Sometimes Antidote can send the file to contact and active chats, sometimes only contact. What's the reason?

**Comment by dvor** [comment]
Thanks for the feedback. Will put file fixes/improvement on the list.

> Sometimes Antidote can send the file to contact and active chats, sometimes only contact. What's the reason?

"Send to active chat" should appear only if there is an open chat. Otherwise you have to pick contact to send file.

**Comment by dvor** [comment]
Depends on https://github.com/Antidote-for-Tox/objcTox/issues/164 https://github.com/Antidote-for-Tox/objcTox/issues/165

**Comment by dvor** [comment]
Everything should be done/fixed, except forwarding messages. Created another issue for last one https://github.com/Antidote-for-Tox/Antidote/issues/204
