### ISSUE TITLE
Infinite "Connecting..." state when returning from lock screen.

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#195]

**Comment by Chuongv** [comment]
I'm trying to reproduce this by locking the screen during the "Connecting..." and then unlocking to check if it's still "Connecting...". But was unable to reproduce this. Are there certain steps in which I can reproduce this?

**Comment by dvor** [comment]
Nope, I just got a feedback from tester that it happens sometimes. Have no idea how to reproduce it, maybe there were issues with network.

**Comment by dvor** [comment]
Wasn't able to reproduce, closing it.
