### ISSUE TITLE
Background running

### ISSUE THREAD

**Issue by TamasSzerb** [Antidote-for-Tox/Antidote#199]
Hello,

I'd be great if the app would work in background, getting messages, while the focus is on other app.

Thanks!

**Comment by dvor** [comment]
Antidote cannot run in background more that 10 minutes due to limitations of iOS. It would be really nice to have push notifications (see https://github.com/Antidote-for-Tox/Antidote/issues/191), but currently it is not possible because of toxcore limitations.

**Comment by masvil** [comment]
@dvor are you evaluating some workarounds?
What do you think about ["Knock" ChatSecure feature](https://chatsecure.org/blog/chatsecure-v32-push/)?

**Comment by dvor** [comment]
I was thinking about something similar. When toxcore will have offline messages Alice will send message to offline storage and ping Bob with push notification.
