### ISSUE TITLE
Release 1.0 to the AppStore

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#202]

**Comment by makoni** [comment]
Any plans?

**Comment by dvor** [comment]
I'm planning to release Antidote to the AppStore in the middle of August. You can check [Backlog](https://github.com/Antidote-for-Tox/Antidote/milestone/1) - all items on top of this issue has to be completed for AppStore release.

**Comment by cryptono** [comment]
@dvor Any new updates?
I'm waiting for the release to the AppStore. It enables me to recommend Tox to other people, only iOS is missing now.

**Comment by dvor** [comment]
@cryptono yeah, release is a bit delayed. I'm now finishing UI update and doing some minor fixes. After that I'll release release candidate to TestFlight, and after week or so will push it to the AppStore.

**Comment by macandchief** [comment]
If it happens, there should be maybe some tam-tam too, like press releases and some short linux magazin articles, diaspora posts, etc. Unfortunately tox and its clients are not really well known yet...

**Comment by Geremia** [comment]
Are there plans to distribute it other ways, in addition to the App Store?

**Comment by dvor** [comment]
@Geremia what other ways do you mean? I'm uploading every ipa in [Release](https://github.com/Antidote-for-Tox/Antidote/releases) section on GitHub, you can download it from there and install yourself (you will need developer account or jailbroken phone for that).

**Comment by Geremia** [comment]
@dvor I didn't know you provided pre-build binaries in GitHub.
thank you

**Comment by Geremia** [comment]
@dvor I synced the IPA using iTunes; however, it doesn't show up on the iPhone. Am I missing something?

**Comment by dvor** [comment]
@Geremia do you have jailbroken iphone? You can find instruction for that on internet - https://duckduckgo.com/?q=cydia+install+ipa

**Comment by Geremia** [comment]
@dvor No, it's not jailbroken, and its owner doesn't want it jailbroken. Do I have to use Test Flight, then?

**Comment by dvor** [comment]
@Geremia if it is not jailbroken there are two options:
- if you have developer account, you can resign ipa file and then install it on device
- you have to use TestFlight (or wait for AppStore release).

**Comment by Geremia** [comment]
@dvor And why do I need to send my "Apple ID email to beta@antidote.im"? (What "Apple ID email" is this, anyways?)
thanks

**Comment by dvor** [comment]
@geremia this is an email you use on your iPhone to login to the AppStore. I need to know it to be able to invite you to the TestFlight.

**Comment by Geremia** [comment]
@dvor Would an ad-hoc signature (`codesign -s - Antidote.ipa`) work?
(Sorry for all the questions; I'm not very familiar with iOS development.)

**Comment by dvor** [comment]
@Geremia unfortunatelly it is not that easy. See instruction in this answer https://stackoverflow.com/a/6921689

**Comment by Geremia** [comment]
@dvor Yeah, I saw that SE answer. It's outdated. Newer versions of `codesign` support ad-hoc signing (cf. [this answer](https://apple.stackexchange.com/a/130504)).

From the [`codesign` manpage](http://www.manpagez.com/man/1/codesign/):

> If identity is the single letter "-" (dash), **ad-hoc signing** is performed.
> Ad-hoc signing does not use an identity at all, and identifies exactly
> one instance of code. Significant restrictions apply to the use of ad-hoc
> signed code; consult documentation before using this.

I checked the .ipa with `codesign -vv Antidote.ipa` after signing it with `codesign -s - Antidote.ipa`, and it said it was signed.

I'll let you know if installs to the iPhone.

**Comment by Geremia** [comment]
@dvor Nope. An ad-hoc signed IPA didn't install via iTunes. I'm going to have to use Test Flight, then.

**Comment by dvor** [comment]
@Geremia because it wasn't actually "signed". ipa file is a zip archive, you have to unarchive it and resign some files inside.

**Comment by Geremia** [comment]
@dvor Ah, I see. I just signed the IPA "wrapper" but not the files inside that really needed signing. Perhaps `codesign -s - --deep Antidote.ipa` will work.

>      --deep  When signing a bundle, specifies that nested code content such as
>              helpers, frameworks, and plug-ins, should be recursively signed
>              in turn. Beware that all signing options you specify will apply,
>              in turn, to such nested content.
>              When verifying a bundle, specifies that any nested code content
>              will be recursively verified as to its full content. By default,
>              verification of nested content is limited to a shallow investiga-
>              tion that may not detect changes to the nested code.
>              When displaying a signature, specifies that a list of directly
>              nested code should be written to the display output. This lists
>              only code directly nested within the subject; anything nested
>              indirectly will require recursive application of the codesign
>              command.

**Comment by Geremia** [comment]
@dvor Using the method in the link you provided (albeit sans the `--resource-rules` flag) or using `--deep` produced the same results: I could see the icon of the app loading on the phone, but then it disappeared, probably because I didn't supply any provisioning file (is there one?) and/or `--resource-rules`, which I didn't see in the ipa.

**Comment by dvor** [comment]
You definitely have to provide provisioning profile (which should include ID of your device). You can get one on Apple developer website.

Also when installing you can take a look at iPhone logs (for example in Xcode "Devices" window) - it should tell you what is wrong.

Anyway, I'm finally finishing with last task and will release master candidate to beta testers (hopefully tomorrow). In a week I'll upload it to the AppStore.

**Comment by Geremia** [comment]
@dvor Great! I'm looking forward to it.
thank you

**Comment by dvor** [comment]
![screen shot 2016-10-03 at 01 30 27](https://cloud.githubusercontent.com/assets/1132979/19024684/ffbe865a-8908-11e6-8060-6f87ebdd3111.png)

**Comment by dvor** [comment]
Okay, first try failed 😅

![screen shot 2016-10-04 at 04 27 42](https://cloud.githubusercontent.com/assets/1132979/19060732/e81468c0-89ea-11e6-8a60-2cbb8ff9bebe.png)

> We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.0.2 on Wi-Fi connected to an IPv6 network. Specifically, the “Confecting…” blue bar indicator failed to complete and never finished what it was working on. Because the app was unable to connect, we were unable to connect multiple accounts or use anything network related.

> Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

---

> We also need access to a video that demonstrates your app in use on a physical iOS device. The demo video should highlight how the app uses the background audio and VoIP functionality (with call-in and call-outs).

**Comment by Geremia** [comment]
@dvor What's the URL for the app?

**Comment by dvor** [comment]
@Geremia Apple rejected app, I have to fix issue with IPv6 before resubmitting it.

**Comment by Geremia** [comment]
@dvor Oh, I thought there'd be a permalink, but I guess not.

**Comment by dvor** [comment]
Blocked by https://github.com/Antidote-for-Tox/Antidote/issues/241

**Comment by dvor** [comment]
One more try

![screen shot 2016-10-26 at 14 52 58](https://cloud.githubusercontent.com/assets/1132979/19726604/f9cb34c4-9b8b-11e6-8c82-e37d8a825275.png)

**Comment by dvor** [comment]
Done!

https://itunes.apple.com/app/antidote-for-tox/id933117605?mt=8
(doesn't work yet, it might take up to 24 hours to actually appear there).

**Comment by Geremia** [comment]
@dvor It's up there already, and it works. thank you
