### ISSUE TITLE
In-App Notifications Appearance & Behavior

### ISSUE THREAD

**Issue by sirnacnud** [Antidote-for-Tox/Antidote#205]
I have been testing Antidote through testflight. I feel the In-App Notifications appearance and behavior could be improved to resemble the look and behavior of the iOS notification banners. The current In-App Notifications are fairly short and animate off the screen by sliding down. 

In my own apps, I have used [LNNotificationsUI](https://github.com/LeoNatan/LNNotificationsUI) for In-App Notifications, as it provides the same look and behavior as the iOS notification banners. If you are open to this change, I can investigate using `LNNotificationsUI` in Antidote and can submit a PR.

**Comment by makoni** [comment]
Yeah, LNNNotificationsUI would look much better than current implementation.

Also, there's [BRYXBanner](https://github.com/bryx-inc/BRYXBanner) as alternative

**Comment by dvor** [comment]
@sirnacnud this is a good idea. You can look at it if you like and submit a pull request.

`NotificationCoordinator` is responsible for showing notifications, basically you would have to change `showNextNotification` method. Also current notification implementation can be removed from `NotificationWindow`.
LNNotificationsUI can be integrated via CocoaPods.

**Comment by sirnacnud** [comment]
Created PR #206

**Comment by dvor** [comment]
Done
