### ISSUE TITLE
Show connecting state unless connected

### ISSUE THREAD

**Issue by nshopik** [Antidote-for-Tox/Antidote#21]
Currently there is no way to tell you are online or offline unless you are have friend who constantly online.  Probably best way to tell user that it's not connected is showing is trying to connect in top bar untill its connected. Just like whatsapp doing it, seem perfect way w/o cluttering interface.

**Comment by dvor** [comment]
Done

**Comment by nshopik** [comment]
Thanks, can you update build in testflight last one expired

**Comment by dvor** [comment]
Yes, I'll publish it to TestFlight today or tomorrow.
