### ISSUE TITLE
Antidote & UTox - .tox file

### ISSUE THREAD

**Issue by RedSoxFan04** [Antidote-for-Tox/Antidote#218]
I’m running UTox on my Mac. I’d like to try Antidote on my iPhone, but I can’t find the .tox file on my Mac. Where is it?

**Comment by dvor** [comment]
You need `tox_save.tox` file which is situated in `~/.config/tox/` folder.

To view content of this directory you can open with Finder, press ⌘⇧G, enter `~/.config/tox/` and press enter.
