### ISSUE TITLE
iPad issues.

### ISSUE THREAD

**Issue by Dirius77** [Antidote-for-Tox/Antidote#22]
I just got the client for the iPad, and here are a couple of bugs.

1) The client doesn't fit an iPads screen nicely.
I know this isn't a bug so much as a lack of feature and lots of other apps do this as well, but it makes an app a lot more visually appealing and easy to use if it will fit the menus to the iPad screen, rather than blowing everything up to 32 point font.

2) The area where you enter a Tox ID will only let you type a couple of letters, at least that I've found (Only the B in groupbot will actually show up if I attempt to type groupbot@tox.me
I'm not sure if this is actually typing and just not displaying, but B is he only letter that works constantly.

**Comment by dvor** [comment]
Added iPad support. Second point is related to Tox DNS, will implement it separately.
