### ISSUE TITLE
[website not clear] Is Antidote available on iOS for simple users?

### ISSUE THREAD

**Issue by yurivict** [Antidote-for-Tox/Antidote#225]
I don't use iOS. One person to whom I recommended qTox, who is a rather an unsophisticated user, asked me if Tox is available for ihone/ipad. The website https://antidote.im left me doubtful as of what the answer is. The website suggests to join the beta testing program.

So what is the answer: are people able to go to the Apple store and install and use Antidote or not?

My suggestion: the website should make a suggestion for the users who can't participate in the beta testing (which is the absolute majority of people): should they still install it, or should they just go away?

**Comment by dvor** [comment]
@yurivict Antidote isn't available on the AppStore yet. People who would like to use it now can participate in beta testing or build the project themselves.

I'll update website and readme as soon as Antidote will be available on the AppStore.
