### ISSUE TITLE
App crashes when disabling/enabling IPv6

### ISSUE THREAD

**Issue by ngrundmann** [Antidote-for-Tox/Antidote#226]
I think the title says it all. 
Antidote crashes when disabling/enabling IPv6.

**Comment by dvor** [comment]
Hi @ngrundmann. Unfortunately I wasn't able to reproduce it.

What device do you have (iPhone, iPad, which number)?
What iOS version are you using?
Is crash reproducible for you? How often does it occur?

**Comment by ngrundmann** [comment]
I had this bug in iOS 10 on an iPhone 6S.
I experienced this every time I disabled/enabled IPv6. 
But good news: with the new version it's fixed and I can't reproduce it

**Comment by dvor** [comment]
That's good. I'm closing issue for now, feel free to reopen it if reoccurs.
