### ISSUE TITLE
Idea for wide spreading 

### ISSUE THREAD

**Issue by iShift** [Antidote-for-Tox/Antidote#227]
Hi, congratulations  with RC release, i have some idea that can help speed Antidote with less pain for users - add authorization (verification) with Telegram/another messengers that support bots.

----
Привет, поздравляю со скорым релизом в AppStore хотел тебе предложить сделать авторизацию (верификацию телефона) через Телеграм или другие сервисы поддерживающие ботов. На мой взгляд без этой функции количество пользователей будет минимальным а если сделать - будут все плюсы от традиционных централизованных мессенджеров - авто поиск контактов из телефонной книги + все плюсы TOX. 

По алгоритму предложил бы поднять бота телеграма который будет ждать обращений. 
1) При установке Antidot будет выбор добавить ли телефон к учетке, если да - продолжать, если нет - всё как сейчас.

2) Приложение обратится к серверу и должно передать TOX ID в ответ сервер вернет UUID который нужно послать в телеграм боту и запишет этот ID в таблице на сервере 

3) Приложение предлагает перейти в телеграм для авторизации - запуск чата с ботом с параметром полученным на втором шаге

4) Пользователь отправляет сообщение боту (и номер), он в ответ отправляет ссылку которую надо открыть в Antidot, на сервере производится запись Telegram ID + телефона

5) Привязка закончена

На основе этого можно запрашивать данные о контактах и добавлять желаемых в список 

Что скажешь? с частью телеграма/сервера готов помочь, для безопастности я бы хранил не телефоны на сервере а их хэши.

**Comment by dvor** [comment]
Насколько я понял, мы на своем сервере привязываем Telegram ID и номер телефона к Tox ID. После этого мы можем найти всех друзей, которые `пользуются Телеграмом` & `установили себе Антидот` & `связали номер и Tox ID`.

Я правильно понял? Боюсь, я сходу вижу довольно много минусов:
- количество таких пользователей будет минимальным
- привязка к Телеграму (или другому сервису)
- централизация
- связь номера и Tox ID
- несовместимость с другими клиентами

**Comment by iShift** [comment]
1) не думаю, круг пользователей телеграмм пересекается с пользователями токса (интересы - секурность) 
При наличии такой связки есть шанс, что человек свяжет сервисы и тогда он получит контакты которые уже пользуются сервисом, а это привычный сценарий использования мессенджера

2) Что ты видишь плохого? Те, кто не захочет - связывать не будут. 

3) согласен, централизация - плохо, но иного варианта поиска контактов из записной книги - нет.

4) в бд можно хранить не номера а их хэши

5) можно сделать API если пойдёт, да и сейчас я что-то не вижу других клиентов для iOS и сильной популярности на андроиде. 

Я понимаю, что это путь компромиссный, но если нет другого гарантированного метода поиска контактов которые уже используют TOX - то это единственный вариант наростить аудиторию.

Опять же, кому не нравится телеграм - можно в дальнейшем добавить любые авторизированные источники которые предоставляют номер телефона

**Comment by dvor** [comment]
1, 2. А зачем вообще привязываться к телеграму? Можно просто читать контакты, отправлять на сервер, готово.
4. Номеров слишком мало - перебрать все хеши ничего не стоит.
5. Так у токса клиенты не только под мобильные платформы - и это решение не совместимо с декстопными клиентами.

В целом я соглашусь, что поиск по контактной книге это хороший путь к популярности. Возможно что-то вроде Tox DNS, только для телефонных номеров было бы приемлемо, но пока я не вижу способа все сделать хорошо.

**Comment by iShift** [comment]
1) как ты проверишь что у пользователя действительно тот номер который от тебе сообщает?
4) хэши можно солить
5) у телеграма/Вайбера тоже есть десктопные клиенты и они работают аналогично

Так давай думать :) 

На мой взгляд единственный способ обеспечить проверку принадлежности номера к пользователю - смс (это стоит денег) лито сервис который уже аутентифицировал номер. 

В toxdns лезть можно, но надо ли?

**Comment by dvor** [comment]
4) Это не поможет. Телефонных номеров не так много, их можно легко перебрать брутфорсом.
5) У телеграма/вайбера декстопные клиенты требуют, чтобы у тебя уже был мобильный. Без него они не работают.
При использовании, например, qTox, у тебя нет ни номера телефона, ни контактной книги. В случае регистрации через телеграм эхта проблема, конечно, отпадает. Но мне кажется, что количество людей, у которых на компьютере установлен телеграм в разы меньше мобильных пользователей с телеграмом.

Итого, я не думаю, что поиск по телефону когда-либо появится в токсе (по крайне мере в таком виде). Централизация, привязка с телеграму, связь номера и Tox ID - вот это все слишком плохо, чтобы использовать.
