### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by urras** [Antidote-for-Tox/Antidote#25]
Yesterday, irungentoo merged the new API branch into master of [irungentoo/toxcore](https://github.com/irungentoo/toxcore). Clients that do not use the new API will no longer work properly. Are there plans to port Antidote to the new API?

**Comment by dvor** [comment]
New API! :tada: 

I've already updated [CocoaPod for toxcore](https://github.com/dvor/toxcore-ios), in nearest future I'll migrate [objcTox](https://github.com/dvor/objcTox) wrapper and then Antidote.

**Comment by urras** [comment]
Wow, that was fast :+1: 
Thanks @dvor

**Comment by dvor** [comment]
It is finally here :)
