### ISSUE TITLE
Consider adding some logic to away/busy statuses

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#254]
I'm not sure that this would be good experience on iOS, need to think about it.

Request from user:

> "Busy" should mean go straight to missed call with an icon +1 & drop down alert, and both calling & text messages have no sound or vibrate. If they try calling three times within 5 minutes (change in settings), then third call or text message will vibrate. 
>
> "Away" should vibrate with no sound but have a custom away message to let people know what you are up to if you wanted so they don't panic or let known how else to contact them. Text messages also vibrate in "Away" mode. However, if their sound is turned on, then sound would be used on the third call or text message in the five minute period (change in settings).

**Comment by altaic** [comment]
Would it be possible to simply use the global iOS Do Not Disturb setting and replicate stock app behavior? That way, Antidote doesn't have to have its own special statuses users have to fiddle with.

**Comment by dvor** [comment]
> simply use the global iOS Do Not Disturb setting and replicate stock app behavior

That what is used now. Tox statuses now are "optional" and don't change any behavior, and I'm pretty fine with that. Closing issue.
