### ISSUE TITLE
Set background image for the chat log screen

### ISSUE THREAD

**Issue by trufae** [Antidote-for-Tox/Antidote#269]
Rather than just white

**Comment by dvor** [comment]
This is debatable feature, I would rather keep classis look and feel that change it to colorful unreadable something. [This](https://www.freeware.de/images/screenshot_slideshow/whatsapp-fuer-android-screenshot-54e84843d9ee2.jpeg) random screenshot reminds me some websites from Web 1.0 https://www.cameronsworld.net/

**Comment by dvor** [comment]
Closing this for now, maybe reconsider it in future.

**Comment by trufae** [comment]
i have a better feeling than this 90’s webstyle design for this feature, all modern chat applications support that. even XChat does. And for example Telegram provides a default list of gradients with soft colors which doesn’t harm the eye. The blue of the messages sent is probably too dark for my taste in the current implementation, will be good to use the blue from the system buttons for example.
