### ISSUE TITLE
视屏时窗口偏移

### ISSUE THREAD

**Issue by nzcool** [Antidote-for-Tox/Antidote#286]
事情视屏的时候，窗口在手机屏幕上偏移。

**Comment by dvor** [comment]
Unfortunately I do not understand Chinese. :-) What I got from online translator:

> Video when the window offset
> Things video, the window on the phone screen offset.

**Comment by ximmyxiao** [comment]
-_-,he means: when in video model , the video window is not fit with the screen (seems got some offset,i guess)

**Comment by dvor** [comment]
Thanks for translation!

Closing this one as there is more general issue about refactoring whole audio/video https://github.com/Antidote-for-Tox/Antidote/issues/263
