### ISSUE TITLE
Antitode could possibly support background notifications

### ISSUE THREAD

**Issue by marmistrz** [Antidote-for-Tox/Antidote#287]
Tox inherently includes audio/video calls so it is allowed by Apple to stay in background: https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

**Comment by masvil** [comment]
Good point. @dvor any thought?

**Comment by dvor** [comment]
Tox doesn't support "voip" as it is allowed by Apple.

> A Voice over Internet Protocol (VoIP) app allows the user to make phone calls using an Internet connection instead of the device’s cellular service. Such an app needs to maintain a persistent network connection to its associated service so that it can receive incoming calls and other relevant data. Rather than keep VoIP apps awake all the time, the system allows them to be suspended and provides facilities for monitoring their sockets for them. When incoming traffic is detected, the system wakes up the VoIP app and returns control of its sockets to it. 

To rephrase this, there should be a server that will ping device on incoming calls. This is not compatible with DHT network which Tox is.

**Comment by dvor** [comment]
Antidote will be able to support background notifications after offline messaging will be added to Tox. See this proposal https://github.com/anoadragon453/tox-offline-messaging-prop/pull/2 for more info.
