### ISSUE TITLE
Not able to archive the project to an IPA File, After archive shows up as 'other items'

### ISSUE THREAD

**Issue by PmAbi1993** [Antidote-for-Tox/Antidote#303]
The project does not export to a normal IPA file when archived. Should I do anything in the PLIST file or any other files to have it exported to IPA??

**Comment by dvor** [comment]
Try to set "Skip install" to "Yes" for both SnapKit and Yaml projects. To do that

- open Antidote in Xcode
- in "submodules" folder select SnapKit.xcodeproj/Yaml.xcodeproj
- select Project -> Build Settings
- set "Skip install" to "Yes".

![screen shot 2017-05-06 at 18 49 41](https://cloud.githubusercontent.com/assets/1132979/25774295/df432ac4-328c-11e7-9123-17a252136134.png)

----

Also you can check comments in https://github.com/Antidote-for-Tox/Antidote/issues/300

**Comment by PmAbi1993** [comment]
Thank you dvor, This helped me big time..
