### ISSUE TITLE
Can't import profile (no app to open file)

### ISSUE THREAD

**Issue by SidorovX86** [Antidote-for-Tox/Antidote#307]
Hi,

I'm trying to import my tox_save.tox file as mentioned in manual.

I've uploaded the file to Yandex.disk.

Then when I tap "Open in another application" I'm getting an error like "There is no application supporting this files type".

**Comment by dvor** [comment]
@SidorovX86 strange, everything worked for me. Can you please check if you are doing same thing that I do on screenshots:

![img_2041](https://user-images.githubusercontent.com/1132979/30369712-b8bf9852-9875-11e7-838e-8a37bf09bc50.PNG)
![img_2042](https://user-images.githubusercontent.com/1132979/30369714-ba845ca4-9875-11e7-89e2-5b9fc08a96b8.PNG)
![img_2043](https://user-images.githubusercontent.com/1132979/30369717-bc8c8eea-9875-11e7-894a-c73ef40923fa.PNG)

**Comment by SidorovX86** [comment]
Hi, I've managed to import profile from mail app.

It seems opening an mail attachemnent works well, but if you try open file in Yandex.disk it fails. May be you can try to repro with Yandex.disk?

**Comment by dvor** [comment]
I used Yandex.disk to create screenshots above.

Anyway, if it works with mail then everything seems to be fine, Antidote provides all needed information. If it doesn't work in Yandex.disk then it is either Yandex.disk bug or iOS one.
