### ISSUE TITLE
Antidote and toxcore version 0.2.0

### ISSUE THREAD

**Issue by hkarel** [Antidote-for-Tox/Antidote#310]
Hi, 
I use qTox assembled wich toxcore version 0.2.x. Audio calls between qTox clients are performed with good sound quality. But when I make a call with qTox to Antidote - the sound quality on the side of the client's Antidote is very poor. There is a constant crackle and gurgling. Antidote-friend can hardly hear me. I already had  a similar situation where qTox clients used different versions of the toxcore (one client less than v0.2, other client equal v0.2)
Tell me which version of the toxcore now uses in Antidote available in AppStore?

**Comment by dvor** [comment]
Currently Antidote uses toxcore v0.1.10. I'll try to update it to 0.2+ in next few weeks.

**Comment by dvor** [comment]
Updated toxcore to 0.2.2, will release new version to the AppStore soon.
