### ISSUE TITLE
Profile exporting does not work

### ISSUE THREAD

**Issue by webjema** [Antidote-for-Tox/Antidote#312]
Hi
I just installed Antidote on my iPhone (6+ latest iOS) and created account.
I'm going to use the same account on PC.
I've tried to export tox profile from Antidote (by email or by saving file) - it does not work.
No errors, no craching.
Thanks.

**Comment by dvor** [comment]
Hi @webjema. Thanks for reporting.

What happens when you press "Export profile" button? Do you get a share sheet? I've tried on latest iOS 11.3.1, for me it works fine.

**Comment by webjema** [comment]
Hi @dvor
Thanks for quick answer.
Yes, I see a share sheet. I can select emails apps and save to cloud/local file. I’ve tried cloud (google drive) and iOS mail app (my common way to send something to my pc). I heard sending sound but nothing sent (nothing in sent folder of the app)
iOS version 11.3(15E216)

**Comment by webjema** [comment]
So. I’ve tried Gmail app - it works.
Sorry for fake bug. For some reason google drive and iOS mail app does not work (but work with other apps)

**Comment by dvor** [comment]
Okay, will close issue.
