### ISSUE TITLE
Remove from App Store

### ISSUE THREAD

**Issue by Ronsor** [Antidote-for-Tox/Antidote#313]
Toxcore is licensed under the GPLv3, which means it cannot be on the app store.

**Comment by AyoungDukie** [comment]
There was discussion (but no apparent resolution that I have found yet) about Toxcore, licensing, and the App Store done here: [Toxcore issue 58](https://github.com/irungentoo/toxcore/issues/58), here: [Toxcore pr 730](https://github.com/irungentoo/toxcore/pull/730), and here: [Toxcore Issue 513](https://github.com/irungentoo/toxcore/issues/513)

I have not had a chance to look into the c-toxcore variant for more info, but given that [GPLv3 and MPLv2.0 are compatible](https://www.fsf.org/blogs/licensing/mpl-2.0-release), and [MPLv2.0 is more friendly for use on stuff like the App Store](https://thenextweb.com/apps/2013/07/18/vlc-for-ios-will-return-to-the-app-store-on-july-19-full-re-write-open-source-licensed-under-mplv2-and-gplv2/), then there may be a way to re-license the toxcore cocoa pod implementation bits to allow compatibility in both directions.

**Comment by dvor** [comment]
Also here https://github.com/irungentoo/toxcore/issues/1064.

I had made a spoken agreement with main tox developers - Antidote won't be doing evil things and will be published under almost compatible license (MPLv2.0 is okay), they won't complain about GPL license violation. For now it works fine.

**Comment by Ronsor** [comment]
This is still legally dangerous, but ok then.
