### ISSUE TITLE
Minor artifacts after renaming a profile until app is restarted

### ISSUE THREAD

**Issue by intelfx** [Antidote-for-Tox/Antidote#32]
After I rename the (only) profile, two artifacts appear:

* I can't copy my Tox ID (at "Settings" tab) by tapping it (the "context menu" does not appear);
* The old profile name is shown in the "Settings" tab (in the profile list, the correct/updated name is shown).

These last until the app is restarted.

iPhone 4S (MD241LL/A), iOS 8.4 (12H143) jailbroken, Antidote 0.3.0 (last in TestFlight). If it can be built under GNU/Linux, then I guess I can locally test patches.

**Comment by dvor** [comment]
> If it can be built under GNU/Linux, then I guess I can locally test patches.

AFAIK you need OS X with Xcode for that.

**Comment by intelfx** [comment]
Ah. Then I won't be able to test... are you able to reproduce?

**Comment by dvor** [comment]
Yes, it's reproducible. Thanks!
