### ISSUE TITLE
Is it possible to disable message logging in Antidote?

### ISSUE THREAD

**Issue by propolisor** [Antidote-for-Tox/Antidote#320]
If not, it'd be a good feature.

**Comment by dvor** [comment]
What do you exactly mean by message logging? Is it chat history? You can always remove particular chats manually if you like.

**Comment by propolisor** [comment]
How do you do this (asking for a friend who isn't exactly tech savvy)?

**Comment by dvor** [comment]
There are several options to delete messages:
- To delete a single message user can long-press on it and select "Delete" option in the popup menu.
- To delete multiple messages user can long-press single message, select "More", tap on messages he want's to remove and press garbage icon in the bottom of the screen.
- To delete whole chat user can either press "Edit" button on the Chats screen, or simply swipe chat to the left and press "Delete" button.
