### ISSUE TITLE
Missing message deletion features

### ISSUE THREAD

**Issue by propolisor** [Antidote-for-Tox/Antidote#321]
[In this issue](https://github.com/Antidote-for-Tox/Antidote/issues/320) I was told that multiple options for deleting messages and chats are available:

> To delete a single message user can long-press on it and select "Delete" option in the popup menu.

>To delete multiple messages user can long-press single message, select "More", tap on messages he want's to remove and press garbage icon in the bottom of the screen.

>To delete whole chat user can either press "Edit" button on the Chats screen, or simply swipe chat to the left and press "Delete" button.

The individual I am corresponding with cannot find these options, which do not seem to be available from the claimed locations. They claim there is no update available for them on the App Store.

Can the developer confirm that these features are available from the latest version made publicly available on the App Store?

**Comment by dvor** [comment]
Message deletion works fine in the latest App Store version 1.3.5.

![IMG_3034](https://user-images.githubusercontent.com/1132979/54757167-f5835980-4be9-11e9-9e3a-39a6564f762a.PNG)
![IMG_3033](https://user-images.githubusercontent.com/1132979/54757157-f320ff80-4be9-11e9-9b44-6b73993cb1cb.PNG)
