### ISSUE TITLE
UI: "Connecting..." bar overlays the first entry in list view

### ISSUE THREAD

**Issue by intelfx** [Antidote-for-Tox/Antidote#35]
It would be nice to shift listview down when that bar appears.

iPhone 4S (MD241LL/A), iOS 8.4 (12H143) jailbroken, Antidote 0.3.0 (last in TestFlight).

Case 1, contact list:
![img_0006](https://cloud.githubusercontent.com/assets/1158172/8499418/544d5204-219b-11e5-98a7-c0437619dc5a.PNG)

Case 2, profile list (BTW, renaming causes reconnect, which is suboptimal):
![img_0008](https://cloud.githubusercontent.com/assets/1158172/8499417/544cc302-219b-11e5-8113-3c2a8c975bad.PNG)

**Comment by dvor** [comment]
Fixed with Swift rewrite.
