### ISSUE TITLE
audio branch doesn't compile, problem with Masonry

### ISSUE THREAD

**Issue by dvor** [Antidote-for-Tox/Antidote#82]
`audio` branch doesn't compile for me. I have following compile errors in many places
> Property 'topMargin' not found on object of type 'UIView *'
> Property 'leftMargin' not found on object of type 'UIView *'
> Property 'rightMargin' not found on object of type 'UIView *'

If there any reason of using `topMargin` instead of `top` (same for other sides)? If not, can you replace margins with non-margin version?

Also, there is no need in specifying side if it is same as for `MASConstraintMaker`. For example
```
// by default `top` side of `view` will be taken, so following two lines are equivalent
// however first one is preferred 
make.top.equalTo(self.view);
make.top.equalTo(self.view.top);
```

Xcode 6.4 (6E35b)
iPhone Simulator 6 (8.4)

**Comment by Chuongv** [comment]
Antidote `audio` branch doesn't compile? Did you do pod update? I'll take care of cleaning up the MASConstraintMaker stuff.

**Comment by dvor** [comment]
Oops, I had old version of Masonry (0.6.1). 0.6.2 works fine.
