### ISSUE TITLE
Mesh network for antidote 

### ISSUE THREAD

**Issue by iShift** [Antidote-for-Tox/Antidote#9]
Apple have interesting framework- multipeer connectivity framework, for example firechat (app) use it. 

It would be good if in the future antidote can support connection using this framework.

If you don't know what is it:
This framework add hybrid mesh function to iOS app, example: 
Alice have Internet connection, bob dont have Internet, but he connected to Alice with bluetooth, Alex have Internet connection. 

Alex can send messages to bob throw Alice, tox core already support relay mode. 

And another brilliant feature - Alice can have Bluetooth connection with Alex, and alex have wifi connection
With bob (alex have wifi and Bluetooth) - Alice can send messages to bob through Alex. 

And main thin all work automatically. 

I know that this is feature for long future :)

**Comment by dvor** [comment]
I will close this issue as I don't see it ever being implemented. Antidote is all about communicating over Tox, while Apple MultipeerConnectivity framework is completely different communication channel.

If someone would like to communicate with mesh network I would suggest using appropriate app for that (e.g. firechat mentioned above).
